import { CssBaseline } from '@mui/material'
import { Header } from '../components/Header'
import { Providers } from 'ui/providers'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <CssBaseline />
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  )
}
